== Kie Server Configuration

The Kie Server should be deployed before running the application and the classic `hellorule` example should be installed and activated. The example is based on the `Person` and `Greeting` facts. The Camel route will periodically add a `Person` fact into the remote knowledge base and retrieve a `Greeting` created by the rule.

The `hellorule` example is installed by default into the Openshift Decision Server xPaaS Image when using the `decisionserver64-basic-s2i` template with the default configuration (the `hellorule` source code is contained in the default git repository used by the template). If the Decision Server xPaaS image is used, access to the rest API is restricted to authenticated users, so the same _username_ and _password_ combination chosen in the Decision Server xPaaS template must be used in the configuration of the current this quickstart.

**Note**: Username and password as well as the service name of the Kie Server for the current quickstart can be set in the `application.properties` file (especially when running this quickstart using the openshift-maven-plugin) or from the Openshift creation wizard when the S2I template is used.

Configuration through the application.properties file can also be useful when running the quickstart locally.